### PR TITLE
Try to optimize map implementations

### PR DESCRIPTION
**Pull request by puzpuzpuz**
Includes the following:
* Updates xsync to v2.3.2
* Optimizes `Inc` and `GetAndReset` methods of `XSyncMapCounterMap`
* Optimizes `GetAndReset` methods in other maps by preallocating `map` of the required size
* Fixes thread safety `MutexCounterMap.GetAndReset` which was returning its internal mutable state instead of creating a copy `map` and returning it

A more general question: are you trying to reproduce a certain use case by all of these implementations? I've noticed that `WorstCase` benchmark inserts map entries like crazy and never touches the old ones. `GetAndReset` is also very costly in that benchmark and the total value that is checked in the benchmark could be calculated in `sync/xsync.Map/MapOf.Range` instead of creating a snapshot copy of the map.

### CODE REVIEW

**Comment by felixge** [comment]
Hah, thanks for this PR! But a bit unexpected, I was just doing some experimentation here, not expecting anybody to take a look 😅 .

My real-world use case is counting requests by endpoint inside of our distributed tracing library, see [draft PR](https://github.com/DataDog/dd-trace-go/pull/1552/files#diff-ad86e517e9501587fea706a500cf65dbf92b14f3c3bfc3f821194125a3c79d46R536-R539).

The expected use case is that the map will grow to ~10-100 items (one for each endpoint) and after that remain stable in terms of keys.

Since this is in a potentially hot code path, I want to reduce the latency of as much as possible.

This repo is just me playing around with different approaches. I'm mostly trying to decide if I prefer the [optimistic locking approach I came up with](https://github.com/felixge/countermap/blob/main/sync_pointer_counter_map.go) or go with xsync.Map. The latter is obviously much better if there is a mixed read/write workload, but as mentioned above, I mostly expect steady-state to be 100% reads.

**Comment by puzpuzpuz** [comment]
I see, thanks for the clarification. I just noticed your repo in the dependents list and decided to take a look.

**Comment by puzpuzpuz** [comment]
Let me close the PR then.

**Comment by felixge** [comment]
Sounds good. But I'll still take a look at your changes when I get a chance :).

**Pull request closed without merging**
